
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coding-sql-pv
  labels:
    app: coding
    tier: sql
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /nfs/coding-sql-pv
    server: 172.16.0.215
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coding-sql-pvc
  labels:
    app: coding
    tier: sql
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  volumeMode: Filesystem
  volumeName: coding-sql-pv
  accessModes:
    - ReadWriteOnce
