name: build-application-workflow

# Build on every push (regardless of branch) for code changes
# Build on PR to ensure the merge is good for code changes
# Allow manual builds
on:
  push:
    paths:
    - '.github/workflows/github-actions.yaml'
    - 'src/**'

  pull_request:
    paths:
    - '.github/workflows/**'
    - 'src/**'

  workflow_dispatch:

env:
  DOCKER_REPO: ghcr.io/${{ github.actor }}

jobs:
  semver:
    name: "Generate SemVer"
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.gitversion.outputs.major }}
      minor: ${{ steps.gitversion.outputs.minor }}
      patch: ${{ steps.gitversion.outputs.patch }}
      majorMinor: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}
      releaseLabel: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}${{ steps.gitversion.outputs.prereleaselabelwithdash }}
      majorMinorReleaseLabel: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}${{ steps.gitversion.outputs.prereleaselabelwithdash }}
      majorReleaseLabel: ${{ steps.gitversion.outputs.major }}${{ steps.gitversion.outputs.prereleaselabelwithdash }}
      semVer: ${{ steps.gitversion.outputs.semver }}
      shorSha: ${{ steps.gitversion.outputs.shortSha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
        
      - name: GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  buildApplciations:
    name: "Build .NET Applciations"
    needs: semver
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build Projects
        working-directory: ./src
        run: |
          dotnet build ./Tsa.IdentityServer.sln \
            --configuration Release \
            --nologo \
            /p:Version=${{ needs.semver.outputs.semVer }}

      - name: Publish IdentityServer App
        working-directory: ./src
        run: |
          dotnet publish ./Tsa.IdentityServer.Web/Tsa.IdentityServer.Web.csproj \
            --configuration Release \
            --no-build \
            --output ${{ runner.temp }}/Tsa.IdentityServer.Web \
            --nologo

      - uses: actions/upload-artifact@v2
        name: Upload Published Blazor Web App
        with:
          name: identity-server
          path: ${{ runner.temp }}/Tsa.IdentityServer.Web
          if-no-files-found: error

  buildDockerContainers:
    name: Build Docker Containers
    needs: [semver, buildApplciations]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build tsa/coding/submissions/identity Image
        run: |
          docker build \
            --tag $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.semVer }} \
            --tag $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.releaseLabel }} \
            --tag $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.majorMinorReleaseLabel }} \
            --tag $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.majorReleaseLabel }} \
            --file src/Tsa.IdentityServer.Web/Dockerfile \
            src/

      #- name: Azure CLI Login
      #  uses: azure/login@v1
      #  if: ${{ github.event_name != 'pull_request' }}
      #  with:
      #    creds: ${{ secrets.AZURE_ACR_CREDENTIALS }}

      #- name: Docker Login
      #  uses: azure/docker-login@v1
      #  if: ${{ github.event_name != 'pull_request' }}
      #  with:
      #    login-server: ${{ env.DOCKER_REPO }}
      #    username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      #    password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      - name: Docker Login to GHCR
        uses: docker/login-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push tsa/coding/submissions/identity Image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.semVer }}
          docker push $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.releaseLabel }}
          docker push $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.majorMinorReleaseLabel }}
          docker push $DOCKER_REPO/tsa/coding/submissions/identity:${{ needs.semver.outputs.majorReleaseLabel }}
